# Generated by Django 3.1.4 on 2020-12-09 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rareuser',
            name='active',
        ),
        migrations.RemoveField(
            model_name='rareuser',
            name='created_on',
        ),
    ]
