# Generated by Django 3.1.4 on 2020-12-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='rareuser',
            name='active',
        ),
        migrations.RemoveField(
            model_name='rareuser',
            name='created_on',
        ),
        migrations.AddField(
            model_name='rareuser',
            name='display_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='bio',
            field=models.CharField(max_length=500),
        ),
    ]
