# Generated by Django 3.1.4 on 2020-12-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_auto_20201209_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='rareuser',
            name='display_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='rareuser',
            name='bio',
            field=models.CharField(max_length=500),
        ),
    ]
