# Generated by Django 3.1.4 on 2020-12-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0003_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['label']},
        ),
    ]
