# Generated by Django 3.1.4 on 2020-12-12 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0008_auto_20201212_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['publication_date']},
        ),
    ]
