# Generated by Django 3.1.4 on 2020-12-13 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0004_auto_20201212_1652'),
        ('rareapi', '0010_auto_20201212_1956'),
    ]

    operations = [
    ]
