# Generated by Django 3.1.4 on 2020-12-16 00:48

from django.db import migrations, models
import rareapi.models.post


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0011_auto_20201215_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.ImageField(blank=True, upload_to=rareapi.models.post.Post.upload_to, verbose_name='Post Image'),
        ),
    ]
